### ISSUE TITLE
Hide Sidebar Button?

### ISSUE THREAD

**Issue by DylanMcD8** [marcosatanaka/sidebar-ios14#2]
Sorry if this isn't the right place to do this, but will you be adding the new button that shows/hides the Sidebar (such as in Photos)?
<img width="359" alt="image" src="https://user-images.githubusercontent.com/41933237/87217709-53294100-c31a-11ea-807a-ac5eaded96cb.png">

Also this is just a personal question, how do you dictate the width of the sidebar? I can't get my app to use the new slimmer width.

**Comment by marcosatanaka** [comment]
You can add this button by setting the `presentsWithGesture` property to `true`  on the `UISplitViewController` instance.

And it's also possible to customize the width by setting the `preferredPrimaryColumnWidthFraction` property. For example:

```
splitViewController.preferredPrimaryColumnWidthFraction = 0.2
```

**Comment by DylanMcD8** [comment]
Thank you!!
